name: jizt
description: Jizt app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  jizt_repository:
    path: packages/jizt_repository
  flutter_bloc: ^6.1.1 # https://pub.dev/packages/flutter_bloc
  rxdart: ^0.25.0 # https://pub.dev/packages/rxdart

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  bloc_test: ^7.1.0 # https://pub.dev/packages/bloc_test

flutter:
  uses-material-design: true
