name: jizt_api
description: Jizt API Dart client.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.2
  json_annotation: ^3.1.1   # Required by json_serializable

dev_dependencies:
  build_runner: ^1.10.11    # Required by json_serializable
  json_serializable: ^3.5.1 # Run: flutter pub run build_runner build
